"""
Integrated pipeline for ORT Henry Ronson School Bell Generator.

Implements the TODO: connects google-ai-script.py and suno-script.py so that
lyrics generated by Google Gemini are automatically passed to the Suno API,
eliminating the need for manual copy-paste.

Usage:
    python pipeline.py
"""

import os
import sys
import requests
import time
import json
from dotenv import load_dotenv
from datetime import datetime, timedelta

load_dotenv()

GOOGLE_API_KEY = os.getenv("GEMINI_API_KEY")
SUNO_API_TOKEN = os.getenv("SUNO_API_TOKEN")

CREATE_TASK_URL = "https://apibox.erweima.ai/api/v1/generate"
STATUS_URL = "https://apibox.erweima.ai/api/v1/generate/record-info?taskId={task_id}"

MAX_CHECKS = 5
CHECK_INTERVAL = 60  # seconds between status polls


def generate_lyrics(log=print) -> str:
    """Generate Hebrew school bell lyrics using Google Gemini based on tomorrow's events in Israel."""
    if not GOOGLE_API_KEY:
        raise ValueError("GEMINI_API_KEY not set in .env")

    from google import genai
    from google.genai.types import Tool, GenerateContentConfig, GoogleSearch

    log("Connecting to Google Gemini...")
    client = genai.Client(api_key=GOOGLE_API_KEY)
    google_search_tool = Tool(google_search=GoogleSearch())

    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents="""אני מבקש ממך לבצע חיפוש מעמיק וממוקד על אירועים חשובים שצפויים להתרחש מחר בישראל,
תוך התמקדות בהיבטים לאומיים, תרבותיים, דתיים, פוליטיים ואקטואליים הרלוונטיים למציאות הישראלית.
השתמש במידע עדכני זמין עד תאריך הידע שלך, חפש ברשת או בנתונים זמינים
אחרים כדי לאסוף פרטים על מאורעות משמעותיים. לאחר מכן, כתוב שיר קצר (4-8 שורות) שישמש כטקסט
לצלצול בית ספר, המשלב את האירועים שמצאת בצורה יצירתית, קליטה ומתאימה לתלמידים, תוך שמירה על
קשר ישיר לאקטואליה ולזיקה הישראלית.""",
        config=GenerateContentConfig(
            tools=[google_search_tool],
            response_modalities=["TEXT"],
        ),
    )

    lyrics = ""
    for part in response.candidates[0].content.parts:
        if hasattr(part, "text") and part.text:
            lyrics += part.text

    return lyrics.strip()


def generate_music(lyrics: str, log=print) -> list:
    """Submit lyrics to Suno API, poll for completion, and download results.

    Returns a list of dicts with keys: folder, audio, image.
    """
    if not SUNO_API_TOKEN:
        raise ValueError("SUNO_API_TOKEN not set in .env")

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": f"Bearer {SUNO_API_TOKEN}",
    }

    payload = {
        "prompt": lyrics,
        "style": "Israeli Pop, High BPM, Drums, Beat, Techno",
        "title": "ORT ISRAEL",
        "customMode": True,
        "instrumental": False,
        "model": "V4",
    }

    log("Submitting generation task to Suno API...")
    create_response = requests.post(CREATE_TASK_URL, headers=headers, json=payload, timeout=30)
    if create_response.status_code != 200:
        raise RuntimeError(f"Task creation failed ({create_response.status_code}): {create_response.text}")

    task_id = create_response.json()["data"]["taskId"]
    log(f"Task created: {task_id}")

    log(f"Waiting {CHECK_INTERVAL}s for initial processing...")
    time.sleep(CHECK_INTERVAL)

    status_response = None
    for attempt in range(1, MAX_CHECKS + 1):
        status_response = requests.get(
            STATUS_URL.format(task_id=task_id), headers=headers, timeout=30
        )
        if status_response.status_code != 200:
            raise RuntimeError(f"Status check failed: {status_response.text}")

        status = status_response.json()["data"]["status"]
        log(f"Check {attempt}/{MAX_CHECKS} — status: {status}")

        if status == "SUCCESS":
            break
        elif status in ("PENDING", "PROCESSING") or "SUCCESS" in status:
            if attempt < MAX_CHECKS:
                log(f"Waiting {CHECK_INTERVAL}s...")
                time.sleep(CHECK_INTERVAL)
        else:
            raise RuntimeError(f"Task failed with status: {status}")
    else:
        raise RuntimeError(f"Timeout: task not completed after {MAX_CHECKS * CHECK_INTERVAL}s")

    base_dir = os.path.dirname(os.path.abspath(__file__))
    tomorrow = datetime.now() + timedelta(days=1)
    results = []

    for version in [1, 2]:
        folder_name = tomorrow.strftime("%d-%m-%y") + f"-{version}"
        folder_path = os.path.join(base_dir, folder_name)
        os.makedirs(folder_path, exist_ok=True)

        song_data = status_response.json()["data"]["response"]["sunoData"][version - 1]
        audio_url = song_data["audioUrl"]
        image_url = song_data["imageUrl"]

        audio_path = os.path.join(folder_path, "song.mp3")
        audio_response = requests.get(audio_url, timeout=60)
        if audio_response.status_code == 200:
            with open(audio_path, "wb") as f:
                f.write(audio_response.content)
            log(f"Saved audio → {folder_name}/song.mp3")

        image_path = os.path.join(folder_path, "cover.jpeg")
        image_response = requests.get(image_url, timeout=60)
        if image_response.status_code == 200:
            with open(image_path, "wb") as f:
                f.write(image_response.content)
            log(f"Saved image → {folder_name}/cover.jpeg")

        results.append({
            "folder": folder_name,
            "audio": os.path.join(folder_name, "song.mp3"),
            "image": os.path.join(folder_name, "cover.jpeg"),
        })

    return results


def run_pipeline(log=print) -> list:
    """Run the full pipeline: Gemini lyrics → Suno music → downloaded files."""
    log("═" * 50)
    log("ORT Henry Ronson — School Bell Pipeline")
    log("═" * 50)

    log("\n[1/2] Generating lyrics with Google Gemini...")
    lyrics = generate_lyrics(log=log)
    log(f"\nLyrics:\n{lyrics}\n")

    log("[2/2] Generating music with Suno API...")
    results = generate_music(lyrics, log=log)

    log("\n✓ Pipeline complete!")
    for r in results:
        log(f"  • {r['folder']}/song.mp3")
    return results


if __name__ == "__main__":
    try:
        run_pipeline()
    except Exception as exc:
        print(f"\nError: {exc}", file=sys.stderr)
        sys.exit(1)
